# server configuration
quarkus.http.port=8080
quarkus.http.host=0.0.0.0

# datasource configuration
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/jlogflow
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres
quarkus.datasource.devservices.enabled=false


quarkus.http.cors.enabled=true
quarkus.http.cors.origins=http://localhost:4200
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.headers=accept,authorization,content-type,x-requested-with

# hibernate (drop-and-create) only for testing
quarkus.hibernate-orm.schema-management.strategy=update
quarkus.hibernate-orm.mapping.format.global=ignore
#quarkus.hibernate-orm.log.sql=true

# kafka configuration
# kafka.bootstrap.servers=localhost:9092
# mp.messaging.incoming.logs.connector=smallrye-kafka
quarkus.kafka.devservices.enabled=false

kafka.bootstrap.servers=localhost:9092
mp.messaging.incoming.logs.connector=smallrye-kafka
mp.messaging.incoming.logs.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
mp.messaging.incoming.logs.failure-strategy=ignore

# open api configuration
quarkus.openapi-generator.codegen.spec.openapi_yaml.generate-apis=false

#quarkus.oidc.auth-server-url=http://localhost:8080/realms
#%test.quarkus.oidc.auth-server-url=${keycloak.url}/realms/quarkus